- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: mateo2 #remplace tout les mateo2 par ton ressource group
        location: francecentral #le datacenter où on veux creer la VM
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: mateo2
        name: myVnet
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: mateo2
        name: mySubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: myVnet
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: mateo2
        allocation_method: Static
        name: myPublicIP
      register: output_ip_address
    - name: Public IP of VM
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}."
    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: mateo2
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: mateo2
        name: myNIC
        virtual_network: myVnet
        subnet_name: mySubnet
        security_group: myNetworkSecurityGroup
        ip_configurations:
          - name: ipconfig1
            private_ip_allocation_method: Dynamic
            public_ip_address_name: myPublicIP
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: mateo2
        name: myVM
        vm_size: Standard_B1s
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "ssh-rsa .." #ta clef publique
        network_interfaces: myNIC
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: '22_04-lts'
          version: latest
    - name: Create inventory file
      copy:
        dest: ./hosts
        content: |
          [apache]
          {{ output_ip_address.state.ip_address }} ansible_user=azureuser ansible_ssh_private_key_file=/home/mateo2-nicoud/.ssh/id_rsa